### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by dorianamouroux** [syrusakbary/aiodataloader#18] opened 2021-06-18 13:30 UTC
I noticed a warning while using the library:

```
/usr/local/lib/python3.7/site-packages/aiodataloader.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
```

which seems to have been fixed in this commit: https://github.com/syrusakbary/aiodataloader/commit/13e696e03b49b2ac33b0dc5bb8d35217d7c5053e

However no releases has been made with that particular fix. Would it be possible to bump to 0.3.0 with that change?

**Comment by antoni-szych-rtbhouse** [comment] 2021-06-23 07:58
duplicate of #16

**Closed as completed** 2022-01-18 08:57 UTC
