### ISSUE TITLE
Python 3.10 compatiblity

### ISSUE THREAD

**Issue by kevinvalk** [syrusakbary/aiodataloader#22] opened 2021-10-19 14:14 UTC
```
  File "/app/src/gateway/graphql/project.py", line 118, in <module>
    from aiodataloader import DataLoader
  File "/venv/lib/python3.10/site-packages/aiodataloader.py", line 2, in <module>
    from collections import Iterable, namedtuple
ImportError: cannot import name 'Iterable' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
```

See (for example) https://github.com/Kozea/pygal/commit/7796f14c80fe82b9435cdc33b7d2939c8331d649 for potential fix

**Comment by markedwards** [comment] 2021-10-23 11:56
This is duplicate of issue #16.  All that needs to happen is to push a release.

**Comment by markedwards** [comment] 2022-01-24 09:59
Resolved as of release 0.2.1.

**Closed as completed by markedwards** 2022-01-24 09:59 UTC
